#!/usr/bin/env bash

set -e

# init setup
echo "Starting configuration"
if [[ -d ./docs/examples ]]; then
    mv ./docs/examples/* ./
    rm -r ./docs/examples
fi

# change to default permissions folders and files
find ./ -type d | xargs chmod 755
find ./ -type f | xargs chmod 644
rm ./skeleton

echo "All configuration right"
